# Generated by Django 5.2.3 on 2025-06-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_tweet_count_comment_tweet_count_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
